dataset:
  name: wikitext-2
  seq_length: 1024
model:
  from_pretrained: false
  name: gpt2-medium
run_id: gpt2-medium_brier-baseline
seed: 43
task_type: language_modeling
training:
  batch_size: 8
  epochs: 10
  learning_rate: 5e-4
  loss: brier
  warmup_steps: 1000
